import { ALL_PERMISSIONS, PERMISSIONS, DEFAULT_ROLES } from '../common/constants/permissions';

export const SEED_ROLES = [
  {
    name: DEFAULT_ROLES.SUPERADMIN,
    description: 'Full system access',
    permissions: ALL_PERMISSIONS,
  },
  {
    name: DEFAULT_ROLES.ADMIN,
    description: 'Manage users, categories, and products',
    permissions: [
      PERMISSIONS.USER_READ,
      PERMISSIONS.USER_CREATE,
      PERMISSIONS.USER_UPDATE,
      PERMISSIONS.USER_DELETE,
      PERMISSIONS.CATEGORY_READ,
      PERMISSIONS.CATEGORY_CREATE,
      PERMISSIONS.CATEGORY_UPDATE,
      PERMISSIONS.CATEGORY_DELETE,
      PERMISSIONS.PRODUCT_READ,
      PERMISSIONS.PRODUCT_CREATE,
      PERMISSIONS.PRODUCT_UPDATE,
      PERMISSIONS.PRODUCT_DELETE,
      PERMISSIONS.DEVICE_READ,
      PERMISSIONS.DEVICE_UPDATE,
      PERMISSIONS.DEVICE_DELETE,
      PERMISSIONS.MEDIA_READ,
      PERMISSIONS.MEDIA_CREATE,
      PERMISSIONS.MEDIA_DELETE,
      PERMISSIONS.IP_BLOCKLIST_READ,
      PERMISSIONS.IP_BLOCKLIST_CREATE,
      PERMISSIONS.IP_BLOCKLIST_DELETE,
      PERMISSIONS.DLQ_READ,
      PERMISSIONS.DLQ_RETRY,
      PERMISSIONS.DLQ_DELETE,
      PERMISSIONS.JOB_READ,
      PERMISSIONS.JOB_MANAGE,
      PERMISSIONS.WEBHOOK_READ,
      PERMISSIONS.WEBHOOK_CREATE,
      PERMISSIONS.WEBHOOK_UPDATE,
      PERMISSIONS.WEBHOOK_DELETE,
    ],
  },
  {
    name: DEFAULT_ROLES.USER,
    description: 'Read-only access',
    permissions: [
      PERMISSIONS.USER_READ,
      PERMISSIONS.CATEGORY_READ,
      PERMISSIONS.PRODUCT_READ,
      PERMISSIONS.DEVICE_READ,
      PERMISSIONS.DEVICE_UPDATE,
      PERMISSIONS.DEVICE_DELETE,
      PERMISSIONS.MEDIA_READ,
      PERMISSIONS.MEDIA_CREATE,
      PERMISSIONS.WEBHOOK_READ,
      PERMISSIONS.WEBHOOK_CREATE,
      PERMISSIONS.WEBHOOK_UPDATE,
      PERMISSIONS.WEBHOOK_DELETE,
    ],
  },
];

export const SEED_USERS = [
  {
    name: 'Super Admin',
    email: 'superadmin@example.com',
    password: 'SuperAdmin@123',
    roleName: DEFAULT_ROLES.SUPERADMIN,
    isEmailVerified: true,
  },
  {
    name: 'Admin User',
    email: 'admin@example.com',
    password: 'AdminUser@123',
    roleName: DEFAULT_ROLES.ADMIN,
    isEmailVerified: true,
  },
  {
    name: 'John Doe',
    email: 'john@example.com',
    password: 'JohnDoe@123',
    roleName: DEFAULT_ROLES.USER,
    isEmailVerified: true,
  },
  {
    name: 'Jane Smith',
    email: 'jane@example.com',
    password: 'JaneSmith@123',
    roleName: DEFAULT_ROLES.USER,
    isEmailVerified: true,
  },
];

export const SEED_CATEGORIES = [
  { name: 'Electronics', description: 'Electronic devices and gadgets' },
  { name: 'Clothing', description: 'Apparel and fashion items' },
  { name: 'Books', description: 'Books and publications' },
  { name: 'Home & Kitchen', description: 'Home appliances and kitchen items' },
  { name: 'Sports', description: 'Sports equipment and accessories' },
];

export const SEED_PRODUCTS = [
  {
    name: 'Wireless Headphones',
    description: 'Bluetooth over-ear headphones with noise cancellation',
    price: 79.99,
    stock: 150,
    categoryName: 'Electronics',
  },
  {
    name: 'Smartphone Case',
    description: 'Shockproof protective case for smartphones',
    price: 14.99,
    stock: 500,
    categoryName: 'Electronics',
  },
  {
    name: 'USB-C Hub',
    description: '7-in-1 USB-C hub with HDMI and ethernet',
    price: 34.99,
    stock: 200,
    categoryName: 'Electronics',
  },
  {
    name: 'Cotton T-Shirt',
    description: '100% organic cotton crew neck t-shirt',
    price: 19.99,
    stock: 300,
    categoryName: 'Clothing',
  },
  {
    name: 'Denim Jeans',
    description: 'Slim fit stretch denim jeans',
    price: 49.99,
    stock: 180,
    categoryName: 'Clothing',
  },
  {
    name: 'Running Jacket',
    description: 'Lightweight waterproof running jacket',
    price: 64.99,
    stock: 100,
    categoryName: 'Clothing',
  },
  {
    name: 'TypeScript Handbook',
    description: 'Comprehensive guide to TypeScript programming',
    price: 39.99,
    stock: 80,
    categoryName: 'Books',
  },
  {
    name: 'Node.js Design Patterns',
    description: 'Advanced patterns for Node.js applications',
    price: 44.99,
    stock: 60,
    categoryName: 'Books',
  },
  {
    name: 'Stainless Steel Blender',
    description: 'High-speed blender with 6 blade system',
    price: 59.99,
    stock: 120,
    categoryName: 'Home & Kitchen',
  },
  {
    name: 'Yoga Mat',
    description: 'Non-slip exercise yoga mat, 6mm thick',
    price: 24.99,
    stock: 250,
    categoryName: 'Sports',
  },
];
